### PR TITLE
Minimal slonik patch for closing stream queries (release)

### PR DESCRIPTION
**Pull request by alxndrsn**
WIP

### CODE REVIEW

**Comment by matthew-white** [comment]
I checked out this PR on the QA server, then followed the repro steps in #482. I'm still able to reproduce a database connection leak by following those steps. However, I actually think that's expected. This patched version of Slonik makes it possible to destroy a stream, but we still need to leverage that ability by making other changes. After discussing with @alxndrsn, it seems like we have three options in this area:

1. Wherever we use `Promise.all()` with a stream, instead use a utility function like the one at https://github.com/getodk/central-backend/issues/482#issuecomment-1126784318
2. Avoid using `Promise.all()` with a stream (https://github.com/getodk/central-backend/issues/482#issuecomment-1240744165)
3. Automatically destroy streams that haven't had a recent read (see #599)

If we want to ship this patched version of Slonik with the upcoming Central patch release, we should also ship one of the three changes above. Ultimately, we'll probably want to make more than one of these changes: I think we want to implement (3), then also either (1) or (2).

**Comment by matthew-white** [comment]
We discussed this in the meeting today, and we're currently thinking that we should ship one of the three options above as part of the patch release. Whichever option we choose, I think we could gain confidence in the change by running the benchmarker against it. @lognaturel also made the point that if streams somehow stop working, that's obviously not a good thing, but there's actually only so much risk there. (It's not like it's a write operation and data would be corrupted.) How does shipping one of those options sound, @alxndrsn? Do you have a preference among them? I don't have a strong preference myself, but let me know if there's a way for me to help. If option (1) seems preferable, I'd be happy to continue working on that utility function.

**Comment by matthew-white** [comment]
I think regardless of whether we ship #608 or the timeout functionality in #599, we should go ahead and merge this PR. @alxndrsn, does that sound right? Is there more that needs to be done for this PR specifically?

**Comment by alxndrsn** [comment]
@matthew-white because this PR wasn't useful, I've re-added stream timeouts, with tests.

**Comment by matthew-white** [comment]
@alxndrsn ran the benchmarker for a few different options:

&nbsp; | Total requests | Successes | Throughput (req/s) | Mean response time (sec) | Max response time (sec) | Min response time (sec) | Response size
-- | --: | --: | --: | --: | --: | --: | --:
#608 | 999 | 11 | 0.0 | 21.6 | 16.8 | 23.4 | 818805
Stream timeout (2 min) | 999 | 53 | 0.2 | 22.2 | 13.3 | 29.9 | 827011
Stream timeout (45 sec) | 1000 | 180 | 0.6 | 25.0 | 14.0 | 36.4 | 871938
Stream timeout (5 sec) | 1000 | 205 | 0.7 | 27.2 | 15.2 | 36.9 | 872616

@alxndrsn wrote on Slack about #608:

> basically throughput is halved... but there don't seem to be any connection leaks

**Comment by matthew-white** [comment]
@alxndrsn taught me how to run the benchmarker, so I've been running it in CircleCI. I ran it for #608, #609, and stream timeouts (this PR). Very surprisingly to me, #609 didn't do any better than #608 (and maybe even did a little worse). Like #608, it performed worse than stream timeouts. (Note that in some cases, I ran the benchmarker multiple times for the same commit and got different results. Below I list the more successful results.)

&nbsp; | CircleCI build | Successes | Throughput (req/s) | Mean response time (sec)
-- | -- | --: | --: | --:
#608 | [**[1]**](https://app.circleci.com/pipelines/github/getodk/central-backend/1023/workflows/9291fc6b-a19d-4b48-b650-5d9bce008291/jobs/1782)[[2]](https://app.circleci.com/pipelines/github/getodk/central-backend/1025/workflows/b4f60fcb-0fb2-4c56-bced-d19d39953adb/jobs/1787) | 57 (5%) | 0.2 | 23.7
#609 | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1024/workflows/b1dadc7f-d9c1-488c-8dca-d342ef81c5f6/jobs/1783)[**[2]**](https://app.circleci.com/pipelines/github/getodk/central-backend/1024/workflows/a6d1e6c3-e2ca-44ec-8fbd-9b390e1f91f0/jobs/1784) | 33 (3%) | 0.1 | 17.8
Stream timeout (2 min) - this PR | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1022/workflows/0a172aca-72b6-4458-a58e-2621f51e2946/jobs/1781) | 91 (9%) | 0.3 | 20.1

Unlike #608, #609 doesn't wait until after a `Promise.all()` to create a stream, so I'm confused about why it's doing so much worse than stream timeouts. Stream timeouts would perform especially well when there's an issue with the client reading data. Is there a chance that the benchmarker just isn't consuming all the streams it's requesting? I changed the benchmarker to send 3 requests every 3 seconds (300 requests total) rather than 10 requests every 3 seconds (1000 requests total). I saw pretty different results:

&nbsp; | CircleCI build | Successes | Throughput (req/s) | Mean response time (sec)
-- | -- | --: | --: | --:
No patch to Slonik (ae09ec577c0e230d63b22bf1fb7c5a552c228b84) | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1018/workflows/0fa07e4e-fddd-4430-ac43-a470402787b0/jobs/1774) | 194 (64%) | 0.6 | 16.0
#608 | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1019/workflows/8d1aee22-ffc1-4df2-ae3a-239984f01b9c/jobs/1775)[**[2]**](https://app.circleci.com/pipelines/github/getodk/central-backend/1027/workflows/e0fa55d4-c783-444d-bbfb-5f8ad98e519e/jobs/1789) | 241 (80%) | 0.8 | 25.4
#609 | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1020/workflows/685fe9ad-4616-496f-9980-be6b97c4c16d/jobs/1776) | 280 (93%) | 0.9 | 20.2
Stream timeout (2 min) - this PR | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1021/workflows/77efb328-a426-4a42-9b68-f077c4b3d6cc/jobs/1777)[**[2]**](https://app.circleci.com/pipelines/github/getodk/central-backend/1021/workflows/10ae4f26-305e-4a3f-96c5-66e2d84cf556/jobs/1778) | 257 (85%) | 0.9 | 18.9
#609 + stream timeout | [[1]](https://app.circleci.com/pipelines/github/getodk/central-backend/1017/workflows/ffcc8128-f5b4-4dc9-89d9-b69f5dd6c2b1/jobs/1773)[**[2]**](https://app.circleci.com/pipelines/github/getodk/central-backend/1026/workflows/869359b4-0291-4720-aba5-a46a39cef109/jobs/1788) | 241 (80%) | 0.8 | 22.7

(Note also the surprising result that #609 + stream timeouts does worse than either one on its own!)

**Review by matthew-white — APPROVED** [review]
See #599 for relevant discussion.

**Comment by matthew-white** [comment]
> There's some variability in the benchmarker results.

@alxndrsn thinks it's possible that some of that variability is from CircleCI itself, specifically the state of the machine on which the benchmarker is run. That's something I'll keep in mind once I continue working on #609.

**Pull request merged**
