### PR TITLE
fixes #858: Submission frame should be reinstantiated

### LINKED ISSUE #858: Extended submission is merged with submitter
When a submission is requested with extended metadata, a `submitter` property is added to the response (the submission object). However, it looks like that submitter object is also merged with the submission object. The submission and the submitter share a couple of properties (`createdAt` and `updatedAt`), and as a result of the merge, it looks like the submission's properties are overwritten by the submitter's. For example, I added `console.log(body)` to the following test:

https://github.com/getodk/central-backend/blob/0057300c8dec811cd63f2898842e12c346e48b09/test/integration/api/submissions.js#L3169-L3181

The body looked like this:

```js
{
  instanceId: 'one',
  submitterId: 5,
  deviceId: null,
  createdAt: '2023-05-05T12:45:20.261Z',
  updatedAt: null,
  reviewState: null,
  userAgent: 'node-superagent/3.8.3',
  currentVersion: {
    submitterId: 5,
    createdAt: '2023-05-05T12:45:20.886Z',
    instanceName: null,
    instanceId: 'one',
    current: true,
    deviceId: null,
    userAgent: 'node-superagent/3.8.3',
    submitter: {
      id: 5,
      type: 'user',
      displayName: 'Alice',
      createdAt: '2023-05-05T12:45:20.261Z',
      updatedAt: null,
      deletedAt: null
    }
  },
  submitter: {
    id: 5,
    type: 'user',
    displayName: 'Alice',
    createdAt: '2023-05-05T12:45:20.261Z',
    updatedAt: null,
    deletedAt: null
  },
  id: 5,
  type: 'user',
  displayName: 'Alice',
  deletedAt: null
}
```

### PR DESCRIPTION
**Pull request by sadiqkhoja**
Closes #858 

#### What has been done to verify that this works as intended?

Added integration test

#### Why is this the best possible solution? Were any other approaches considered?

Other option was to change the behaviour of `forApi()` but looks too risky to me

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

None, I'll create a separate PR to verify/fix same for entities

#### Does this change require updates to the API documentation? If so, please update docs/api.md as part of this PR.

No

#### Before submitting this PR, please make sure you have:

- [x] run `make test-full` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

**Comment by matthew-white** [comment]
In the `ExtendendSubmission` assertion, what do you think about changing `should.containDeep` to `should.eqlInAnyOrder`? I think that'd help prevent this issue and also similar issues in the future.

https://github.com/getodk/central-backend/blob/85806dfc9862fb79ad4f7b25891634efadec0b95/test/assertions.js#L98-L101

**Comment by sadiqkhoja** [comment]
> In the `ExtendendSubmission` assertion, what do you think about changing `should.containDeep` to `should.eqlInAnyOrder`? I think that'd help prevent this issue and also similar issues in the future.
> 

not sure how that will help here? The issue is not related to the order or existence of the properties

**Comment by matthew-white** [comment]
Right now the extended submission has extra top-level properties: `id`, `type`, `displayName`, `deletedAt`. `containDeep` is happy to ignore them, but `eqlInAnyOrder` would have flagged them.

**Comment by matthew-white** [comment]
Sorry, I probably should highlighted that in #858. The issue isn't just that properties are overwritten, it's also that there are extra properties.

**Comment by sadiqkhoja** [comment]
I see. I will replace every `containDeep` with `eqlInAnyOrder` assertion.js in a separate PR

**Review by ktuite — APPROVED** [review]

**Pull request merged**
