### PR TITLE
Upgrade to node 20.10 and postgres 14.10

### PR DESCRIPTION
**Pull request by lognaturel**
#### What has been done to verify that this works as intended?
Ran locally, clicked around and downloaded some submission zips.

#### Why is this the best possible solution? Were any other approaches considered?
Latest minor versions available.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
There could be some new bugs introduced in these versions.

#### Does this change require updates to the API documentation? If so, please update docs/api.md as part of this PR.
No.

#### Before submitting this PR, please make sure you have:

- [x] run `make test-full` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

**Comment by lognaturel** [comment]
In CI I see 

```
  1) api: /forms/:id/submissions
       .csv.zip GET
         should include all repeat rows @slow:
     Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

I can't seem to repro locally. It's a timeout, right?

**Comment by matthew-white** [comment]
For posterity: Previously, in the one failing test, 50 concurrent requests were sent in a `Promise.all()`. The test passed for @lognaturel locally, but not in CircleCI. When she reduced the number of requests from 50 to 30, the test passed in CircleCI. I came across ladjs/supertest#709, which mentions issues with SuperTest and Node 20 when there are many concurrent requests. I deparallelized the one test, and then it passed. I assume that the failing test was just due to that GitHub issue and not a performance degradation in Backend. The soak tester continues to pass.

**Comment by matthew-white** [comment]
@lognaturel, I think we also need to bump Node in oidc-dev/playwright-tests/package.json.

**Comment by matthew-white** [comment]
Should we bump Postgres for `run-docker-postgres` in the makefile? I'm actually not sure what the effect would be for someone who's already created that database locally. We could look into that later, but if you happen to know that it's OK, feel free to bump the version there!

**Review by matthew-white — APPROVED** [review]
To review, I searched the codebase for the strings "18.17" and "14.6". I left a couple of comments above, but this PR is looking great. Thank you, @lognaturel!

**Comment by matthew-white** [comment]
Do we need to wait until we have a PR to the `central` repo to merge this PR? I'm wondering what the effect on staging would be to merge this PR without also making a change to `central`.

**Comment by lognaturel** [comment]
Since no code changes were needed, we can just go ahead and get the Central PR in first whether or not it's necessary. Give me a sec.

**Comment by lognaturel** [comment]
Infrastructure PR at https://github.com/getodk/central/pull/562

**Comment by matthew-white** [comment]
@ktuite, you use `run-docker-postgres` locally, right? You might be in a good position to check whether it's easy to bump the Postgres version. Also probably not a big deal to leave it as-is.

**Pull request merged**
