### PR TITLE
bugfix: comment submission response format is bizarre

### LINKED ISSUE #516: Comment submission response format is bizarre
### Request

```bash
curl 'https://example.com/v1/projects/1/forms/some_form/submissions/uuid%3A3c4b658c-12f0-48c9-a22d-cec305be99a0/comments' \
    ...auth headers etc... \
    --data-raw $'{"body":"hi"}'
```

### Response

```json
{"id":{},"submissionId":{},"actorId":{},"body":{"0":"h","1":"i"},"createdAt":{}}
```

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #516

### CODE REVIEW

**Comment by alxndrsn** [comment]
If adding a test, can we just remove the comment body from the response?  There doesn't seem much benefit to echoing the data that the user just sent to the server.

**Comment by matthew-white** [comment]
I agree that there's not a ton of benefit. I think that's what we do with POST responses in general though, so it seems nice to be consistent.

**Comment by issa-tseng** [comment]
by REST conventions you should totally reply with the data as newly represented no? as opposed to RPC etc

**Comment by alxndrsn** [comment]
@matthew-white test added :+1:

**Review by matthew-white — APPROVED** [review]

**Comment by matthew-white** [comment]
Ah looks like CircleCI is failing on the `master` branch with some small linting issues.

**Comment by matthew-white** [comment]
> Ah looks like CircleCI is failing on the `master` branch with some small linting issues.

Those are now resolved as of #550 — thanks, @sadiqkhoja!

**Pull request merged**
