### PR TITLE
eslint: disable import/no-unresolved in ./oidc-dev

### LINKED ISSUE #977: eslint fails on playwright-tests dir
```
$ make test
node lib/bin/enforce-node-version.js
npx eslint --cache --max-warnings 0 .

/odk/central-backend/oidc-dev/playwright-tests/playwright.config.js
  10:29  error  Unable to resolve path to module '@playwright/test'  import/no-unresolved
```

This may be correct, but not very helpful - lint should probably not need every sub-project's dependencies to install.

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #977

### CODE REVIEW

**Comment by alxndrsn** [comment]
@ktuite can you give this branch a try and see if the issue with `make lint` is resolved?

**Comment by ktuite** [comment]
Still getting the errors :(

```
$ make test
node lib/bin/enforce-node-version.js
npx eslint --cache --max-warnings 0 .

/Users/ktuite/Desktop/code/odk/central-backend/oidc-dev/playwright-tests/playwright.config.js
  10:29  error  Unable to resolve path to module '@playwright/test'  import/no-unresolved

/Users/ktuite/Desktop/code/odk/central-backend/oidc-dev/playwright-tests/src/global-setup-teardown.js
  23:43  error  Unable to resolve path to module 'http-proxy-middleware'  import/no-unresolved

/Users/ktuite/Desktop/code/odk/central-backend/oidc-dev/playwright-tests/src/oidc-login.spec.js
  10:26  error  Unable to resolve path to module '@playwright/test'  import/no-unresolved

/Users/ktuite/Desktop/code/odk/central-backend/oidc-dev/playwright-tests/src/utils.js
  22:28  error  Unable to resolve path to module '@playwright/test'  import/no-unresolved

✖ 4 problems (4 errors, 0 warnings)

make: *** [lint] Error 1
```

**Comment by alxndrsn** [comment]
@ktuite I think probably simplest just to disable it for now.  Can you give the PR another try now?

**Review by ktuite — APPROVED** [review]
sorry for taking a million years to try this again. it does indeed work now!

**Pull request merged**
