### PR TITLE
CSRF token: handle failed url-decoding

### PR DESCRIPTION
**Pull request by alxndrsn**
Related:

* https://github.com/getodk/central-backend/pull/1269
* https://github.com/getodk/central-backend/pull/1268
* https://github.com/getodk/central-backend/pull/1267
* https://github.com/getodk/central-backend/pull/1270

Ref #1260

### CODE REVIEW

**Comment by matthew-white** [comment]
My feeling overall when looking at these PRs is that the `try`/`catch` blocks make the main logic slightly harder to follow. Is there an alternative to `try`/`catch` that we could consider? How about a function that returns something like `null` or `Option.none()` if the string can't be decoded? Something like:

```js
const tryDecodeURI = (s) => {
  try {
    return decodeURIComponent(s);
  } catch (error) {
    return null;
  }
};
```

or

```js
const tryDecodeURI = (s) => {
  try {
    return Option.of(decodeURIComponent(s));
  } catch (error) {
    return Option.none();
  }
};
```

I think a function like this could reduce the number of nested blocks or otherwise enable us to structure the code in a different way from what `try`/`catch` requires.

**Comment by alxndrsn** [comment]
> Is there an alternative to `try`/`catch` that we could consider? How about a function that returns something like `null` or `Option.none()` if the string can't be decoded?

How would this work for something like https://github.com/getodk/central-backend/pull/1270:

```js
// Given an OData URL subpath, returns a contextStack: [ [ pathName: String, tableId: String? ] ]
// that the subpath represents.
const extractPathContext = (subpath) => {
  const rawParts = subpath.split('/').slice(1);
  let parts;
  try {
    parts = rawParts.map(part => decodeURIComponent(part));
  } catch (err) {
    throw Problem.user.unparseableODataExpression({ reason: 'URL-decoding failed' });
  }
  return parts.map((part) => {
    const match = /^([^(]+)\('((?:uuid:)?[a-z0-9-]+)'\)$/i.exec(part);
    return (match == null) ? [ part, null ] : [ match[1], match[2] ];
  });
};
```

**Comment by alxndrsn** [comment]
@matthew-white looks good; is that preferred to:

```js
const extractPathContext = (subpath) =>
  subpath.split('/').slice(1).map((part) => {
    const decoded = decodeURI(part);
    if (decoded.isEmpty())
      throw Problem.user.unparseableODataExpression({ reason: 'URL-decoding failed' });
    const match = /^([^(]+)\('((?:uuid:)?[a-z0-9-]+)'\)$/i.exec(decoded.get());
    return (match == null) ? [ part, null ] : [ match[1], match[2] ];
  });
  ```

**Comment by matthew-white** [comment]
An approach that uses `Option` sounds great to me. :+1:

**Review by matthew-white — APPROVED** [review]

**Pull request merged**
