### PR TITLE
Add timing for migrations

### PR DESCRIPTION
**Pull request by alxndrsn**
See how long is spent re-migrating the DB in CI.

### CODE REVIEW

**Comment by alxndrsn** [comment]
Interesting comparison of the time this takes on CI vs locally:

environment | time spent re-migrating DB | total test time | % time spent re-migrating
---|---|---|---
CI | 8s | 6m | 2%
local | 22s | 2m | 18%

**Comment by alxndrsn** [comment]
@matthew-white I'd be interested what timings you get on your machine

**Comment by alxndrsn** [comment]
Closing this, as it isn't for merging.

**Comment by matthew-white** [comment]
I'm actually having trouble at the moment running some of the `testContainerFullTrx()` tests. I think it's some issue with my local setup. Maybe @ktuite could get these timings on her machine?

**Comment by matthew-white** [comment]
I got these timings now that I'm no longer having trouble running tests locally. I'm getting 1m total test time, with 12s spent re-migrating the database.

**Comment by alxndrsn** [comment]
@matthew-white thanks for sharing - I've updated the table above.

**Comment by alxndrsn** [comment]
**The different ratio observed on CI is likely because CI is running `make test-full`, and locally we're running `make test`.**

**Comment by matthew-white** [comment]
Ah good call, that makes a lot of sense!

**Pull request closed without merging**
