### PR TITLE
move test reinit to mocha's after hooks

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes https://github.com/getodk/central-backend/issues/499

### CODE REVIEW

**Comment by issa-tseng** [comment]
by doing it this way aren't you now repaving the database after every test? only some tests use reinit.

**Comment by matthew-white** [comment]
It'd be pretty cool if we could get `testServiceFullTrx()` and `testContainerFullTrx()` to automatically clean up after the test has finished (succeeded, failed, or timed out). I think it'd be easy to forget to call `reinitAfter()`. What do you think about an approach that uses a flag? Something like:

```js
let reinitAfter = false;
afterEach(function() {
  if (reinitAfter) {
    this.timeout(5000);
    reinitAfter = false;
    return initialize();
  }
});

// ...

const testServiceFullTrx = (test) => {
  reinitAfter = true;
  return () => test(augment(request(service(baseContainer))), baseContainer);
};
```

**Comment by alxndrsn** [comment]
@matthew-white maybe the most ergonomic would be to create a wrapper function which, given a test function, will wrap it with:

```javascript
describe('...', () => {
  before(appropriateSetup);
  after(appropriateTearDown);
  it('...', () => ...test code...);
});
```

**Comment by alxndrsn** [comment]
Alternative implementation at https://github.com/getodk/central-backend/pull/557

**Comment by alxndrsn** [comment]
@matthew-white PR with your suggestion of [automatic cleanup](https://github.com/getodk/central-backend/pull/552#issuecomment-1199700608) at https://github.com/getodk/central-backend/pull/558.

**Comment by matthew-white** [comment]
Closing now that #558 is merged!

**Pull request closed without merging**
